const plan = [
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Тануки',
        dt_start: new Date('29 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('29 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Тануки',
        dt_start: new Date('01 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('01 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('04 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('04 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('08 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('08 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 45,
        role: 'waiter',
        employee_name: 'Полина',
        restaurant: 'Тануки',
        dt_start: new Date('29 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('29 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 45,
        role: 'waiter',
        employee_name: 'Полина',
        restaurant: 'Тануки',
        dt_start: new Date('28 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('28 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('27 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('27 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('03 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('03 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('17 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('17 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('10 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('10 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 34,
        role: 'waiter',
        employee_name: 'Владислав',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('25 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('25 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 90,
        role: 'waiter',
        employee_name: 'Дмитрий',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('18 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('18 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 77,
        role: 'waiter',
        employee_name: 'Сергей',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('11 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('11 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 77,
        role: 'waiter',
        employee_name: 'Сергей',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('01 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('01 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 78,
        role: 'waiter',
        employee_name: 'Линда',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('08 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('08 August 2022 14:00 UTC').toISOString(),
    },
];

const fact = [
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Тануки',
        dt_start: new Date('29 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('29 August 2022 12:00 UTC').toISOString(),
    },
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Тануки',
        dt_start: new Date('01 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('01 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('04 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('04 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 123,
        role: 'waiter',
        employee_name: 'Александр',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('08 August 2022 09:00 UTC').toISOString(),
        dt_end: new Date('08 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 45,
        role: 'waiter',
        employee_name: 'Полина',
        restaurant: 'Тануки',
        dt_start: new Date('29 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('29 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 45,
        role: 'waiter',
        employee_name: 'Полина',
        restaurant: 'Тануки',
        dt_start: new Date('28 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('28 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('27 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('27 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('03 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('03 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('17 August 2022 11:00 UTC').toISOString(),
        dt_end: new Date('17 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 12,
        role: 'waiter',
        employee_name: 'Юлия',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('10 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('10 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 34,
        role: 'waiter',
        employee_name: 'Владислав',
        restaurant: 'Вкусно — и точка!',
        dt_start: new Date('25 August 2022 09:00 UTC').toISOString(),
        dt_end: new Date('25 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 90,
        role: 'waiter',
        employee_name: 'Дмитрий',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('18 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('18 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 77,
        role: 'waiter',
        employee_name: 'Сергей',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('11 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('11 August 2022 12:00 UTC').toISOString(),
    },
    {
        user_id: 77,
        role: 'waiter',
        employee_name: 'Сергей',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('01 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('01 August 2022 14:00 UTC').toISOString(),
    },
    {
        user_id: 78,
        role: 'waiter',
        employee_name: 'Линда',
        restaurant: 'Бургер Кинг',
        dt_start: new Date('08 August 2022 06:00 UTC').toISOString(),
        dt_end: new Date('08 August 2022 14:00 UTC').toISOString(),
    },
];

export { plan, fact };
